version: '3.9'

services:
  db:
    container_name: postgres-db
    image: postgres:14-alpine
    user: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile-api
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_READ_HOST=db
      - WAIT_HOSTS:postgres:5432
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PORT=${DATABASE_PORT}
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    links:
      - db
      - cache

  migration:
    build:
      context: .
      dockerfile: Dockerfile-migration
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
  cache:
    container_name: cache
    image: 'redis:alpine'
    command: "redis-server"
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  pg-data:
    external: false
  cache:
    driver: local
