export const ERROR_CODES = {
  ERROR_ALREADY_EXISTS: 'ERROR_ALREADY_EXISTS',
  ERROR_INVALID_INPUT: 'ERROR_INVALID_INPUT',
  ERROR_UNAUTHENTICATED: 'ERROR_UNAUTHENTICATED',
  ERROR_OBJECT_NOT_FOUND: 'ERROR_OBJECT_NOT_FOUND',
  ERROR_OBJECT_ALREADY_EXISTS: 'ERROR_OBJECT_ALREADY_EXISTS',
  ERROR_INVALID_ARGUMENTS: 'ERROR_INVALID_ARGUMENTS',
  ERROR_UNAUTHORIZED: 'ERROR_UNAUTHORIZED',
  ERROR_FORBIDDEN: 'ERROR_FORBIDDEN',
  ERROR_THIRD_PARTY_SERVICE: 'ERROR_THIRD_PARTY_SERVICE',
  ERROR_BANNED_USER: 'ERROR_BANNED_USER',
  ERROR_BAD_REQUEST: 'ERROR_BAD_REQUEST',
  ERROR_CONFLICT: 'ERROR_CONFLICT',
  ERROR_NOT_IMPLEMENTED: 'ERROR_NOT_IMPLEMENTED',
  ERROR_RECORD_ARCHIVE: 'ERROR_RECORD_ARCHIVE',
  ERROR_INTERNAL_SERVER_ERROR: 'ERROR_INTERNAL_SERVER_ERROR',
  ERROR_INVALID_CREDENTIALS: 'ERROR_INVALID_CREDENTIALS',
  ERROR_PHONE_NUMBER_ALREADY_EXITS: 'ERROR_PHONE_NUMBER_ALREADY_EXITS',
  ERROR_ACCOUNT_LOCKED: 'ERROR_ACCOUNT_LOCKED',
  ERROR_ACCOUNT_DISABLED: 'ERROR_ACCOUNT_DISABLED',
  ERROR_ACCOUNT_NOT_VERIFIED: 'ERROR_ACCOUNT_NOT_VERIFIED',
  ERROR_LOGIN_TIMEOUT: 'ERROR_LOGIN_TIMEOUT',
  ERROR_INCORRECT_OTP: 'ERROR_INCORRECT_OTP',
  ERROR_INVALID_VERIFICATION_TOKEN: 'ERROR_INVALID_VERIFICATION_TOKEN',
  ERROR_OTP_EXPIRED: 'ERROR_OTP_EXPIRED',
  ERROR_MULTIFACTOR_AUTH_REQUIRED: 'ERROR_MULTIFACTOR_AUTH_REQUIRED',

  ERROR_EMAIL_ALREADY_REGISTERED: 'ERROR_EMAIL_ALREADY_REGISTERED',
  ERROR_USERNAME_ALREADY_TAKEN: 'ERROR_USERNAME_ALREADY_TAKEN',
  ERROR_WEAK_PASSWORD: 'ERROR_WEAK_PASSWORD',
  ERROR_INVALID_EMAIL_FORMAT: 'ERROR_INVALID_EMAIL_FORMAT',
  ERROR_INVALID_PHONE_FORMAT: 'ERROR_INVALID_PHONE_FORMAT',
  ERROR_REGISTRATION_DISABLED: 'ERROR_REGISTRATION_DISABLED',
  ERROR_USER_SUSPENDED: 'ERROR_USER_SUSPENDED',
  ERROR_USER_SUSPENDED_RETIES_EXCEEDED: 'ERROR_USER_SUSPENDED_RETIES_EXCEEDED',

  ERROR_INVALID_TOKEN: 'ERROR_INVALID_TOKEN',
  ERROR_EXPIRED_TOKEN: 'ERROR_EXPIRED_TOKEN',
  ERROR_REFRESH_TOKEN_INVALID: 'ERROR_REFRESH_TOKEN_INVALID',
  ERROR_TOKEN_REVOKED: 'ERROR_TOKEN_REVOKED',
  ERROR_TOKEN_REQUIRED: 'ERROR_TOKEN_REQUIRED',

  ERROR_PASSWORD_MISMATCH: 'ERROR_PASSWORD_MISMATCH',
  ERROR_PASSWORD_CHANGE_FAILED: 'ERROR_PASSWORD_CHANGE_FAILED',
  ERROR_EMAIL_UPDATE_FAILED: 'ERROR_EMAIL_UPDATE_FAILED',
  ERROR_PROFILE_UPDATE_FAILED: 'ERROR_PROFILE_UPDATE_FAILED',
  ERROR_ACCOUNT_DELETION_FAILED: 'ERROR_ACCOUNT_DELETION_FAILED',
  ERROR_UNAUTHORIZED_ACCESS: 'ERROR_UNAUTHORIZED_ACCESS',

  ERROR_EMAIL_NOT_VERIFIED: 'ERROR_EMAIL_NOT_VERIFIED',
  ERROR_PHONE_NOT_VERIFIED: 'ERROR_PHONE_NOT_VERIFIED',
  ERROR_VERIFICATION_CODE_INVALID: 'ERROR_VERIFICATION_CODE_INVALID',
  ERROR_VERIFICATION_CODE_EXPIRED: 'ERROR_VERIFICATION_CODE_EXPIRED',

  ERROR_ACCESS_DENIED: 'ERROR_ACCESS_DENIED',
  ERROR_ROLE_NOT_ASSIGNED: 'ERROR_ROLE_NOT_ASSIGNED',
  ERROR_RESOURCE_FORBIDDEN: 'ERROR_RESOURCE_FORBIDDEN',

  ERROR_SOCIAL_AUTH_FAILED: 'ERROR_SOCIAL_AUTH_FAILED',
  ERROR_SOCIAL_ACCOUNT_ALREADY_LINKED: 'ERROR_SOCIAL_ACCOUNT_ALREADY_LINKED',
  ERROR_SOCIAL_TOKEN_INVALID: 'ERROR_SOCIAL_TOKEN_INVALID',

  ERROR_SERVER_ERROR: 'ERROR_SERVER_ERROR',
  ERROR_SERVICE_UNAVAILABLE: 'ERROR_SERVICE_UNAVAILABLE',
  ERROR_INVALID_REQUEST: 'ERROR_INVALID_REQUEST',
  ERROR_MISSING_FIELDS: 'ERROR_MISSING_FIELDS',
  ERROR_UNSUPPORTED_OPERATION: 'ERROR_UNSUPPORTED_OPERATION',
  ERROR_UNABLE_TO_COMPLETE_OPERATION: 'ERROR_UNABLE_TO_COMPLETE_OPERATION',

  ERROR_NOT_FOUND: 'ERROR_NOT_FOUND',

  ERROR_USER_NOT_FOUND: 'ERROR_USER_NOT_FOUND',

  ERROR_NO_THING_TO_UPDATE: 'ERROR_NO_THING_TO_UPDATE',

  NO_FILE_PROVIDED: 'NO_FILE_PROVIDED',

  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',

  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
};
